Dev
UjjwalBudha/Game_Friday-May-24 pull request #1
Opened 2024-06-11 04:05 UTC by UjjwalBudha

completed the task and sent for review

2024-06-11 04:13 UTC, mukes137 requested changes

2024-06-11 04:13 UTC, mukes137 commented on ansible/playbook.yml
> +# - hosts: i-003db8f1004f8f52b
remove the commented lines.

2024-06-11 04:13 UTC, mukes137 commented on ansible/playbook.yml
> +- hosts: i-090b0d4c36dbcc597
do not use instance id as hostname.
make it more dynamic in nature.

2024-06-11 04:13 UTC, mukes137 commented on ansible/roles/django/tasks/main.yml
> +    dest: /etc/nginx/sites-available/reverse_proxy.conf
use variables instead of hardcoded path.

2024-06-11 04:13 UTC, mukes137 commented on ansible/roles/django/tasks/main.yml
> +    src: /etc/nginx/sites-available/reverse_proxy.conf
use variables.

2024-06-11 04:13 UTC, mukes137 commented on ansible/roles/django/handlers/main.yml
> +- name: Restart Nginx
why are you restarting nginx in django task?

2024-06-11 04:13 UTC, mukes137 commented on ansible/roles/nginx/vars/main.yml
> +# home_dir: /root
remove the commented lines.

2024-06-11 04:35 UTC, UjjwalBudha commented on ansible/playbook.yml
> +# - hosts: i-003db8f1004f8f52b
uncommented this part

2024-06-11 04:49 UTC, UjjwalBudha commented on ansible/roles/django/tasks/main.yml
> +    dest: /etc/nginx/sites-available/reverse_proxy.conf
used variables

2024-06-11 04:51 UTC, UjjwalBudha commented on ansible/roles/django/handlers/main.yml
> +- name: Restart Nginx
in my case django is the frontend part and after changing  the reverse proxy conf i have restarted the frontend server which will now interact with the backend server[nginx]

2024-06-11 04:51 UTC, UjjwalBudha commented on ansible/roles/nginx/vars/main.yml
> +# home_dir: /root
removed the commented parts

2024-06-11 04:52 UTC, UjjwalBudha commented on ansible/roles/django/tasks/main.yml
> +    src: /etc/nginx/sites-available/reverse_proxy.conf
used variables

2024-06-11 05:06 UTC, UjjwalBudha commented on ansible/playbook.yml
> +- hosts: i-090b0d4c36dbcc597
updated it

2024-06-12 05:08 UTC, mukes137 approved these changes

2024-06-12 05:43 UTC, merged